wildfly:
  rules:
    title: "\\[WFLY-\\d+\\]\\s+.*|WFLY-\\d+\\s+.*"
    body: "Body text"
    titleBody: "TitleBody text
    directories: ["directory1", "directory2"]
    notify: ["notify1", "notify2"]
