wildfly:
  rules:
    - title: "test"
    - body: "test"
      notify: [xstefank,petrberan]
  format:
    title-check:
      pattern: "\\[WFLY-\\d+\\]\\s+.*|WFLY-\\d+\\s+.*"
      message: "Wrong content of the title!"
